# Generated by Django 5.1.4 on 2026-06-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterprofile',
            name='cover',
        ),
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
    ]
