# Generated by Django 5.0.6 on 2026-06-20 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('queue_position', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('in_progress', 'Jarayonda'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi'), ('no_show', 'Kelmadi')], default='pending', max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='masters.masterprofile')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='masters.service')),
            ],
            options={
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['master', 'start_at'], name='bookings_bo_master__52623c_idx')],
            },
        ),
    ]
