# Generated by Django 5.1.4 on 2026-06-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_walk_in_name_booking_walk_in_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='master_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
