# Generated by Django 5.1.4 on 2026-06-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_master_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
