# Generated by Django 5.1.4 on 2026-06-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_client_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirm_stage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
