# Generated by Django 5.1.4 on 2026-06-26 13:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, max_length=160)),
                ('actor_tg_id', models.BigIntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('login', 'Ilovaga kirdi'), ('bot_start', 'Botda /start bosdi'), ('joined', 'Yangi foydalanuvchi'), ('registered', 'Telefonni tasdiqladi'), ('became_master', "Usta bo'ldi"), ('published', "Profilni e'lon qildi"), ('left_master', 'Usta rejimidan chiqdi'), ('discount_created', "Chegirma e'lon qildi"), ('booking_created', 'Bron qildi'), ('booking_status', "Bron holatini o'zgartirdi"), ('review_created', 'Baho qoldirdi')], db_index=True, max_length=24)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'created_at'], name='adminpanel__kind_18dc97_idx')],
            },
        ),
    ]
